feat: add CLI test
Move-Agency/actions-templates pull request #29
Opened 2024-05-13 08:41 UTC by SMillerDev

2024-05-13 13:38 UTC, pprkut requested changes

2024-05-13 13:38 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +          extensions: 'autoload_psr-pprkut/autoload-psr@0.2.0,pecl_http,uuid'
Make make these variable too

2024-05-13 13:38 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
`support/setup.sh` is maybe a bit better here. Allows for potentially other things too.

One thing we might want to look into is InfluxDB logging, for example. Currently, `cli.php` runs send stats to InfluxDB indicating to come from `production` because we don't change that config anywhere.

2024-05-13 13:42 UTC, SMillerDev commented on .github/workflows/php-decomposer.yml
> +          extensions: 'autoload_psr-pprkut/autoload-psr@0.2.0,pecl_http,uuid'
Should I make it like:
```suggestion
          extensions: '{{ inputs.php-extensions }},pecl_http,uuid'
```
or rather:
```suggestion
          extensions: '{{ inputs.php-run-extensions }}'
```

2024-05-13 13:46 UTC, SMillerDev commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
Would you rather I try and set configuration? Or run with `--analytics=local`?

2024-05-13 13:55 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +          extensions: 'autoload_psr-pprkut/autoload-psr@0.2.0,pecl_http,uuid'
I'd stay consistent with the `php-tests`, where we also use it for all extensions

2024-05-13 13:57 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
`--analytics=local` only works for pipelines. It doesn't impact the analytics from `cli.php` itself. We could fix that, but until that point `--analytics=local` wouldn't help.
We don't necessarily need analytics though, so ideally we'd turn them off somehow indeed. But marking the environment as `ci` or some such is the next best thing.

2024-05-15 08:31 UTC, SMillerDev commented on .github/workflows/php-decomposer.yml
> +    name: "PHP-${{ matrix.php-versions }}: CLI Test"
Do you want to make the file configurable? Or the whole call?

2024-05-16 12:25 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +      php-run-extensions:
Maybe we should rename the other one to `phpunit-php-extensions` instead? Or some such

2024-05-16 12:25 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
I'd still prefer running `support/setup.sh` here

2024-05-16 12:25 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        default: '-vvv'
I think it makes more sense to combine these two. We're just appending them later anyway

2024-05-16 12:29 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
We can even make it optional, like, only run it if it exists. That way we don't need to special case projects that don't have one (though all of ours do)

2024-05-30 16:05 UTC, SMillerDev commented on .github/workflows/php-decomposer.yml
> +        run: touch MAINTENANCE.php
```suggestion
        run: support/setup.sh
```

2024-07-08 13:34 UTC, pprkut commented on .github/workflows/php-decomposer.yml
> +        default: '-vvv'
No, it's fine. I missed that, apparently. Let's leave it split then.
However, can we make the names a bit more generic? Like, `php-test-file` instead of `cli-test-file`, or `exec-test-file`

2026-05-15 16:44 UTC, closed without merging