feat: add check for pipelines
Move-Agency/actions-templates pull request #33
Opened 2024-06-28 08:38 UTC by SMillerDev

2024-06-28 12:32 UTC, brianstoop requested changes

2024-07-01 11:33 UTC, brianstoop approved these changes

2024-07-08 13:40 UTC, pprkut commented on pipeline-check/pipeline.schema.json
> +    "additionalProperties": false,
Conceptually, I think this should go to the pipeline code. If we ever split that up into open source repos, it might even deserve its own repo.

2024-07-09 08:41 UTC, SMillerDev commented on pipeline-check/pipeline.schema.json
> +    "additionalProperties": false,
Do you have a specific recommendation where to store this? Because I'm not sure what to change now.

2025-01-08 07:50 UTC, marcella-galambos-move approved these changes

2026-05-15 16:45 UTC, closed without merging